### ISSUE TITLE
Create login command

### ISSUE THREAD

**Issue by Timothee-Cardoso** [secman-team/secman#15]
`login` command is like this

```sh
secman login

# now it's ask
# do you want to login by gh cli or git
❯ gh cli
❯ git
```

let's do this bro, it's a great addition for **secman**

**Comment by abdfnx** [comment]
From where you get these great ideas

**Comment by abdfnx** [comment]
the command was created

**Comment by abdfnx** [comment]
this command was `secman auth login` 👍
