### ISSUE TITLE
Version Checker

### ISSUE THREAD

**Issue by Timothee-Cardoso** [secman-team/secman#29]
when I finish from inserting a new password, update checker it's takes a long time, I think it a bug

**Comment by abdfnx** [comment]
Yes, I found the bug, it's in `sm` folder

```powershell
$p=$args[0]

switch($p.ToLower()) {
    "--sm" {
        ruby v_checker.rb -c;
        Break
    }

    ...
}
```

and now **v_checker.rb** doesn't has `-c` flag

so I delete this flag

```powershell
$p=$args[0]

switch($p.ToLower()) {
    "--sm" {
        ruby v_checker.rb;
        Break
    }

    ...
}
```

**Comment by abdfnx** [comment]
the error was return

**Comment by abdfnx** [comment]
This error only occurs in the Windows system 😐

**Comment by abdfnx** [comment]
The Error Was Fixed 👍👍👍
