### ISSUE TITLE
Make secman self-reliant

### ISSUE THREAD

**Issue by abdfnx** [secman-team/secman#32]
@iMRxM7mD @Timothee-Cardoso, we must make secman self-reliant, that's means we don't `sm` folder

so first

1. create _**ruby**_ commander in `shell` package like **powershell** and **bash**.
2. all version checks it's on secman.

**Comment by Timothee-Cardoso** [comment]
This is a challenge that I want to take 💪

**Comment by abdfnx** [comment]
This is the morale that I want

**Comment by abdfnx** [comment]
that's means secman doesn't `secman-sync`

so we must create `sync` command

like `secman start-sync` --> `secman sync start`

**Comment by Timothee-Cardoso** [comment]
Todo List 📄

1. make secman doesn't needs `sm` folder.
2. create _**ruby**_ commander in **shell** package.
3. make all version checks in secman.
4. create `sync` command with.
    - **start**.
    - **pull**.
    - **push**.

**Comment by abdfnx** [comment]
nice 👌

**Comment by abdfnx** [comment]
let's do it

**Comment by abdfnx** [comment]
I think we should make secman without ruby, so we don't need to create _**ruby**_ commander.

**Comment by abdfnx** [comment]
it's done
