### ISSUE TITLE
Fetching in windows

### ISSUE THREAD

**Issue by abdfnx** [secman-team/secman#57]
when I fetching my new password in windows, it's always asking my github username and my password

```
secman fetch

[================>   ] 🔗 Fetching... Username for 'https://github.com':
[========>           ] 🔗 Fetching... om':
```

so I think we have to change **fetch** method of `windows`

from

```powershell
$lastDir = pwd
cd $HOME/.secman
git pull
cd $lastDir
```

to

```powershell
Remove-Item $HOME/.secman -Recurse -Force
secman repo clone $username/.secman
```

**Comment by Timothee-Cardoso** [comment]
change it to `secman sync clone`

**Comment by abdfnx** [comment]
or we can create a new command `secman sync fetch-clone`
